### PR TITLE
JS files into dist

### PR DESCRIPTION
**Pull request by xtine**
So `openFEC` copies over files from `/dist`, so we need to make sure the correct files are committed and also remove the outdated files.

### CODE REVIEW

**Review by patphongs — APPROVED** [review]
Thanks @xtine. I believe this should work!

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by LindsayYoung** [comment]
I can test this out at the end of the day

**Review by LindsayYoung — APPROVED** [review]
Thanks!

**Pull request merged**
